# Generated by Django 4.1.4 on 2022-12-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelosApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juju',
            old_name='user_id',
            new_name='id',
        ),
    ]
